# Data Preprocessing Exercices

In [78]:

import numpy as np
from numpy.random.mtrand import standard_normal, random

In [79]:
# load the wines dataset (../data/wines.csv)
import pandas as pd

df=pd.read_csv("../data/wines.csv")

In [80]:

df.head(5)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,NaN,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,NaN,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

In [81]:
# check for missing values in the dataset

df.isnull().sum()

alcohol                         15
malic_acid                       0
ash                             23
alcalinity_of_ash                0
magnesium                        0
total_phenols                    0
flavanoids                       0
nonflavanoid_phenols             0
proanthocyanins                  0
color_intensity                  0
hue                              0
od280/od315_of_diluted_wines     0
proline                          0
target                           0
dtype: int64

In [82]:
# if any, impute the missing values with the mean of the column

df.fillna(df.mean(), inplace=True)
df.isnull().sum()

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
target                          0
dtype: int64

In [83]:
# scale the dataset using two different scaling methods
#   #######StandardScaler##########
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_Standard = scaler.fit_transform(df)
df_Standard = pd.DataFrame(df_Standard, columns=df.columns)
df_Standard.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,1.602583,-0.562250,0.254968,-1.169593,1.913905,0.808997,1.034819,-0.659563,1.224884,0.251717,0.362177,1.847920,1.013009,-1.213944
1,0.263988,-0.499413,-0.853428,-2.490847,0.018145,0.568648,0.733629,-0.820719,-0.544721,-0.293321,0.406051,1.113449,0.965242,-1.213944
2,0.212003,0.021231,0.000000,-0.268738,0.088358,0.808997,1.215533,-0.498407,2.135968,0.269020,0.318304,0.788587,1.395148,-1.213944
3,0.000000,-0.346811,0.522512,-0.809251,0.930918,2.491446,1.466525,-0.981875,1.032155,1.186068,-0.427544,1.184071,2.334574,-1.213944
4,0.315972,0.227694,1.936672,0.451946,1.281985,0.808997,0.663351,0.226796,0.401404,-0.319276,0.362177,0.449601,-0.037874,-1.213944

In [84]:
df_Standard.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
count,1.780000e+02,1.780000e+02,1.780000e+02,1.780000e+02,1.780000e+02,178.000000,1.780000e+02,1.780000e+02,1.780000e+02,1.780000e+02,1.780000e+02,1.780000e+02,1.780000e+02,1.780000e+02
mean,-1.077790e-15,-1.197544e-16,-8.831887e-16,-3.991813e-17,-3.991813e-17,0.000000,-3.991813e-16,3.592632e-16,-1.197544e-16,2.494883e-17,1.995907e-16,3.193450e-16,-1.596725e-16,1.596725e-16
std,1.002821e+00,1.002821e+00,1.002821e+00,1.002821e+00,1.002821e+00,1.002821,1.002821e+00,1.002821e+00,1.002821e+00,1.002821e+00,1.002821e+00,1.002821e+00,1.002821e+00,1.002821e+00
min,-2.556160e+00,-1.432983e+00,-3.834630e+00,-2.671018e+00,-2.088255e+00,-2.107246,-1.695971e+00,-1.868234e+00,-2.069034e+00,-1.634288e+00,-2.094732e+00,-1.895054e+00,-1.493188e+00,-1.213944e+00
25%,-8.146863e-01,-6.587486e-01,-4.616672e-01,-6.891372e-01,-8.244151e-01,-0.885468,-8.275393e-01,-7.401412e-01,-5.972835e-01,-7.951025e-01,-7.675624e-01,-9.522483e-01,-7.846378e-01,-1.213944e+00
50%,0.000000e+00,-4.231120e-01,0.000000e+00,1.518295e-03,-1.222817e-01,0.095960,1.061497e-01,-1.760948e-01,-6.289785e-02,-1.592246e-01,3.312687e-02,2.377348e-01,-2.337204e-01,7.996036e-02
75%,7.968267e-01,6.697929e-01,5.893977e-01,6.020883e-01,5.096384e-01,0.808997,8.490851e-01,6.095413e-01,6.291754e-01,4.939560e-01,7.131644e-01,7.885875e-01,7.582494e-01,1.373864e+00
max,2.382348e+00,3.109192e+00,3.312611e+00,3.154511e+00,4.371372e+00,2.539515,3.062832e+00,2.402403e+00,3.485073e+00,3.435432e+00,3.301694e+00,1.960915e+00,2.971473e+00,1.373864e+00

In [85]:
# ########MinMaxScaler########
from sklearn.preprocessing import MinMaxScaler

scalerMinMax = MinMaxScaler()
df_MinMax =scalerMinMax.fit_transform(df)
df_MinMax = pd.DataFrame(df_MinMax, columns=df.columns)
df_MinMax.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,0.842105,0.191700,0.572193,0.257732,0.619565,0.627586,0.573840,0.283019,0.593060,0.372014,0.455285,0.970696,0.561341,0.0
1,0.571053,0.205534,0.417112,0.030928,0.326087,0.575862,0.510549,0.245283,0.274448,0.264505,0.463415,0.780220,0.550642,0.0
2,0.560526,0.320158,0.536519,0.412371,0.336957,0.627586,0.611814,0.320755,0.757098,0.375427,0.447154,0.695971,0.646933,0.0
3,0.517598,0.239130,0.609626,0.319588,0.467391,0.989655,0.664557,0.207547,0.558360,0.556314,0.308943,0.798535,0.857347,0.0
4,0.581579,0.365613,0.807487,0.536082,0.521739,0.627586,0.495781,0.490566,0.444795,0.259386,0.455285,0.608059,0.325963,0.0

In [86]:
df_MinMax.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,0.517598,0.315484,0.536519,0.458502,0.323278,0.453487,0.356386,0.437460,0.372523,0.322363,0.388170,0.491460,0.334446,0.469101
std,0.203062,0.220780,0.140309,0.172142,0.155244,0.215811,0.210730,0.234818,0.180555,0.197806,0.185831,0.260070,0.224613,0.387517
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.352632,0.170455,0.471925,0.340206,0.195652,0.262931,0.182489,0.264151,0.264984,0.165529,0.245935,0.244505,0.158702,0.000000
50%,0.517598,0.222332,0.536519,0.458763,0.304348,0.474138,0.378692,0.396226,0.361199,0.290956,0.394309,0.553114,0.282097,0.500000
75%,0.678947,0.462945,0.618984,0.561856,0.402174,0.627586,0.534810,0.580189,0.485804,0.419795,0.520325,0.695971,0.504280,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [87]:
# perform feature selection using two different methods

In [88]:
##### KBest ######
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression

#Separating Features and Target
X = df.drop('target', axis=1)
Y = df['target']

KBest= SelectKBest(score_func=f_regression, k=4)
data = KBest.fit_transform(X,Y)
#features names
featurenamesK=X.columns.values[KBest.get_support()]
data = pd.DataFrame(data, columns=featurenamesK)
data

     total_phenols  flavanoids  od280/od315_of_diluted_wines  proline
0             2.80        3.06                          3.92   1065.0
1             2.65        2.76                          3.40   1050.0
2             2.80        3.24                          3.17   1185.0
3             3.85        3.49                          3.45   1480.0
4             2.80        2.69                          2.93    735.0
..             ...         ...                           ...      ...
173           1.68        0.61                          1.74    740.0
174           1.80        0.75                          1.56    750.0
175           1.59        0.69                          1.56    835.0
176           1.65        0.68                          1.62    840.0
177           2.05        0.76                          1.60    560.0

[178 rows x 4 columns]

In [89]:
# #####Variance Threshold
from sklearn.feature_selection import VarianceThreshold

X = df.drop('target', axis=1)

varThresh = VarianceThreshold(threshold=0.5)
X_var= varThresh.fit_transform(X)
#features names
featurenamesV = X.columns.values[varThresh.get_support()]
dataVar=pd.DataFrame(X_var,columns= featurenamesV)
dataVar

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,color_intensity,od280/od315_of_diluted_wines,proline
0,14.230000,1.71,15.6,127.0,3.06,5.64,3.92,1065.0
1,13.200000,1.78,11.2,100.0,2.76,4.38,3.40,1050.0
2,13.160000,2.36,18.6,101.0,3.24,5.68,3.17,1185.0
3,12.996871,1.95,16.8,113.0,3.49,7.80,3.45,1480.0
4,13.240000,2.59,21.0,118.0,2.69,4.32,2.93,735.0
...,...,...,...,...,...,...,...,...
173,13.710000,5.65,20.5,95.0,0.61,7.70,1.74,740.0
174,13.400000,3.91,23.0,102.0,0.75,7.30,1.56,750.0
175,13.270000,4.28,20.0,120.0,0.69,10.20,1.56,835.0
176,13.170000,2.59,20.0,120.0,0.68,9.30,1.62,840.0
177,14.130000,4.10,24.5,96.0,0.76,9.20,1.60,560.0

In [90]:
# compare the results of the two feature selection methods
#treinar em modelos e ver as accuracy
#Explicar apenas as features que foram retiradas estatiscamente e porque foram retiradas

In [91]:
#Para comparar os resultados dos dois metodos de feature selection, vou treinar um modelo com as features selecionadas pelo dois metódos e ver a accuracy de cada um.

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

#Dividir em dados de treino e dados de teste
X_trainK, X_testK, y_train, y_test = train_test_split(X[featurenamesK],Y,test_size=0.2,random_state=42)
X_trainV, X_testV, _,_ =train_test_split(X[featurenamesV],Y,test_size=0.2,random_state=42)

#Treinar o modelo
model_K = RandomForestClassifier(random_state=42)
model_K.fit(X_trainK,y_train)
y_predK= model_K.predict(X_testK)
accuracyK= accuracy_score(y_test,y_predK)

model_V = RandomForestClassifier(random_state=42)
model_V.fit(X_trainV,y_train)
y_predV= model_V.predict(X_testV)
accuracyV = accuracy_score(y_test,y_predV)

print("Accuracy com Kbest é:", accuracyK)
print("Accuracy com varianceThreshold é de:", accuracyV)

Accuracy com Kbest é: 0.8333333333333334
Accuracy com varianceThreshold é de: 1.0

 Com base nesse resultado podemos ver que o modelo usando as feature do metódo varianceThreshold  teve uma melhor perfomace , tendo a accuracy de 100%.